import { createElement } from 'lwc';
import Mc_SubscriptionDataViewer from 'c/mc_SubscriptionDataViewer';

describe('c-mc-subscription-data-viewer', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-mc-subscription-data-viewer', {
            is: Mc_SubscriptionDataViewer
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});